baseURL = "https://example.com"
title = "Website Name"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Your site description"
  copyright = "Copyright Â© 2020 Your Name"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true
